name: run_first

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: list file in workdir 
        run: | 
          echo " workdir: ${{ github.workspace }} "
          ls ${{ github.workspace }}
          mkdir build 
          cd build
          cmake --version 
          cmake -D CMAKE_CONFIGURATION_TYPES=RelWithDebInfo ../
        shell: pwsh
      - name: build by cmake
        run: |
          cmake --build . --config RelWithDebInfo
          ls
          ./CMakeProject1.exe
